apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: mydb
spec:
  memorySize: 2GB
  replication: true
  databasePort: 12001
  databaseSecretName: mydb-noauth
  redisVersion: "7.2"