apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec-CLUSTER
spec:
  # Add fields here
#  rackAwarenessNodeLabel: "topology.kubernetes.io/zone"
#  redisOnFlashSpec:
#    enabled: true
#    storageClassName: managed-premium
  ingressOrRouteSpec:
    apiFqdnUrl: api.CLUSTER.DNS_ZONE
    dbFqdnSuffix: -db.CLUSTER.DNS_ZONE
    ingressAnnotations:
      haproxy-ingress.github.io/ssl-passthrough: "true"
      kubernetes.io/ingress.class: haproxy
    method: ingress
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 4000m
      memory: 16Gi